const TYPEFORM_OFFER_FORM_ID = "vBOEFE8R";
const TYPEFORM_INTEREST_FORM_ID = "g0qtEedy";
const RADAR_VALIDATE_ADDRESS_API_URL =
  "https://api.radar.io/v1/addresses/validate";

export {
  TYPEFORM_OFFER_FORM_ID,
  RADAR_VALIDATE_ADDRESS_API_URL,
  TYPEFORM_INTEREST_FORM_ID,
};
